# Generated by Django 2.2.12 on 2020-07-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200719_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
