# Generated by Django 2.1.5 on 2020-03-26 17:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200326_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 17, 39, 57, 820675, tzinfo=utc), verbose_name='Published Date'),
        ),
    ]
