# Generated by Django 2.1.5 on 2020-03-26 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200326_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 18, 26, 45, 166509), verbose_name='Published Date'),
        ),
    ]
