# Generated by Django 2.2.12 on 2020-11-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='products',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
