# Generated by Django 2.2.12 on 2020-07-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200712_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Discount Price'),
        ),
        migrations.AddField(
            model_name='item',
            name='image1',
            field=models.ImageField(blank=True, default='ProductsDefault.jpg', null=True, upload_to='Products/%Y/%m/%d/', verbose_name='2nd Image'),
        ),
        migrations.AddField(
            model_name='item',
            name='image2',
            field=models.ImageField(blank=True, default='ProductsDefault.jpg', null=True, upload_to='Products/%Y/%m/%d/', verbose_name='3rd Image'),
        ),
        migrations.AddField(
            model_name='item',
            name='image3',
            field=models.ImageField(blank=True, default='ProductsDefault.jpg', null=True, upload_to='Products/%Y/%m/%d/', verbose_name='4th Image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='ProductsDefault.jpg', null=True, upload_to='Products/%Y/%m/%d/', verbose_name='Main Image'),
        ),
    ]
