# Generated by Django 2.2.12 on 2020-07-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200713_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
