# Generated by Django 2.2.12 on 2020-07-12 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200713_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalitem',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='item',
            name='summary',
        ),
    ]
