# Generated by Django 2.2.12 on 2020-07-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200717_2128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['amount']},
        ),
        migrations.AddField(
            model_name='coupon',
            name='amount',
            field=models.FloatField(default=124),
            preserve_default=False,
        ),
    ]
