# Generated by Django 2.2.12 on 2020-07-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200718_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
