# Generated by Django 2.2.12 on 2020-07-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200718_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refrence_code',
            field=models.CharField(default='ashikfsdffasdfsdfsdf', max_length=50),
            preserve_default=False,
        ),
    ]
