# Generated by Django 2.1.5 on 2020-02-07 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='tutirial_published',
            new_name='tutorial_published',
        ),
    ]
