# Generated by Django 2.1.5 on 2020-02-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200207_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='tutorial_tittle',
            new_name='tutorial_title',
        ),
    ]
