# Generated by Django 2.1.5 on 2020-02-07 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200207_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 21, 13, 54, 508007), verbose_name='Date published'),
        ),
    ]
