# Generated by Django 2.1.5 on 2020-02-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200207_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=200)),
                ('news_author', models.CharField(max_length=50)),
                ('news_content', models.TextField()),
                ('news_published', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
