# Generated by Django 2.1.5 on 2020-03-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200326_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_date',
            field=models.DateTimeField(verbose_name='Published Date'),
        ),
    ]
