# Generated by Django 2.2.12 on 2020-07-16 14:52

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200714_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('apartment_address', models.CharField(max_length=200)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('zipcode', models.CharField(max_length=5)),
                ('same_billing_address', models.BooleanField(default=False)),
                ('save_info', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('C', 'Credit Card'), ('M', 'Master Card'), ('P', 'Paypal'), ('Py', 'Payoneer')], max_length=2)),
            ],
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Item'},
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.BillingAddress'),
        ),
    ]
