# Generated by Django 2.2.12 on 2020-07-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200717_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Payment',
            new_name='payment',
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='payment_method',
            field=models.CharField(choices=[('C', 'Credit Card/Master Card'), ('P', 'Paypal'), ('Py', 'Payoneer')], max_length=2),
        ),
    ]
