# Generated by Django 2.2.12 on 2020-07-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200718_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivering',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='recieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_request',
            field=models.BooleanField(default=False),
        ),
    ]
